
-- alx_book_store.sql-- alx
-- Schema for an online bookstore

CREATE DATABASE IF NOT EXISTS ALX_BOOK_STORE;
USE ALX_BOOK_STORE;

-- AUTHORS: Stores information about authors.
CREATE TABLE IF NOT EXISTS AUTHORS (
    author_id INT AUTO_INCREMENT PRIMARY KEY,
    author_name VARCHAR(215) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- CUSTOMERS: Stores information about customers.
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_name VARCHAR(215) NOT NULL,
    email VARCHAR(215) NOT NULL,
    address TEXT
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- BOOKS: Stores information about books available in the bookstore.
CREATE TABLE IF NOT EXISTS BOOKS (
    book_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(130) NOT NULL,
    author_id INT NOT NULL,
    price DOUBLE NOT NULL,
    publication_date DATE,
    CONSTRAINT FK_BOOKS_AUTHORS FOREIGN KEY (author_id)
        REFERENCES AUTHORS(author_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ORDERS: Stores information about orders placed by customers.
CREATE TABLE IF NOT EXISTS ORDERS (
    order_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (customer_id)
        REFERENCES CUSTOMERS(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- ORDER_DETAILS: Stores information about the books included in each order.
CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    orderdetailid INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    book_id INT NOT NULL,
    quantity DOUBLE NOT NULL,
    CONSTRAINT FK_ORDERDETAILS_ORDERS FOREIGN KEY (order_id)
        REFERENCES ORDERS(order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_ORDERDETAILS_BOOKS FOREIGN KEY (book_id)
        REFERENCES BOOKS(book_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT CHK_QUANTITY_POSITIVE CHECK (quantity > 0)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;

-- Helpful indexes
CREATE INDEX IDX_BOOKS_AUTHOR_ID ON BOOKS(author_id);
CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON ORDERS(customer_id);
CREATE INDEX IDX_ORDERDETAILS_ORDER_ID ON ORDER_DETAILS(order_id);
